Repository quangdvn/homestay-server, pull requests merged in 2020-10, with the labels that each got.

#16 Task-1
  .github/workflows/ci.yml
  .gitignore
  .rails_best_practices.yml
  .rspec
  .rubocop.yml
  .rubocop_disabled.yml
  .rubocop_enabled.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  README.md
  Rakefile
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/.keep
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/application_record.rb
  app/models/concerns/.keep
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.text.erb
  bin/bundle
  bin/rails
  bin/rake
  bin/setup
  bin/spring
  config.ru
  config/application.rb
  config/boot.rb
  config/cable.yml
  config/credentials.yml.enc
  config/database.yml
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/application_controller_renderer.rb
  config/initializers/backtrace_silencers.rb
  config/initializers/cors.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/initializers/mime_types.rb
  config/initializers/wrap_parameters.rb
  config/locales/en.yml
  config/puma.rb
  config/routes.rb
  config/spring.rb
  config/storage.yml
  db/schema.rb
  db/seeds.rb
  lib/tasks/.keep
  log/.keep
  public/robots.txt
  spec/rails_helper.rb
  spec/spec_helper.rb
  storage/.keep
  tmp/.keep
  tmp/pids/.keep
  vendor/.keep
Labels: good first issue

#17 Task 2
  .github/workflows/cd.yml
  app/models/amenity.rb
  app/models/booking.rb
  app/models/bookmark.rb
  app/models/city.rb
  app/models/district.rb
  app/models/host_information.rb
  app/models/place.rb
  app/models/review.rb
  app/models/rule.rb
  app/models/user.rb
  db/migrate/20201005152327_create_users.rb
  db/migrate/20201005153056_create_host_informations.rb
  db/migrate/20201005154146_create_cities.rb
  db/migrate/20201005154247_create_amenities.rb
  db/migrate/20201005154705_create_districts.rb
  db/migrate/20201005154947_create_rules.rb
  db/migrate/20201005160040_create_places.rb
  db/migrate/20201005162105_create_places_amenities.rb
  db/migrate/20201005163038_create_places_rules.rb
  db/migrate/20201005164043_create_bookings.rb
  db/migrate/20201005164916_create_bookmarks.rb
  db/migrate/20201005165126_create_reviews.rb
  db/schema.rb
  spec/factories/amenities.rb
  spec/factories/bookings.rb
  spec/factories/bookmarks.rb
  spec/factories/cities.rb
  spec/factories/districts.rb
  spec/factories/host_informations.rb
  spec/factories/places.rb
  spec/factories/reviews.rb
  spec/factories/rules.rb
  spec/factories/users.rb
  spec/models/amenity_spec.rb
  spec/models/booking_spec.rb
  spec/models/bookmark_spec.rb
  spec/models/city_spec.rb
  spec/models/district_spec.rb
  spec/models/host_information_spec.rb
  spec/models/place_spec.rb
  spec/models/review_spec.rb
  spec/models/rule_spec.rb
  spec/models/user_spec.rb
Labels: documentation

#18 Task-3
  .gitignore
  Gemfile
  Gemfile.lock
  app/models/amenity.rb
  app/models/city.rb
  app/models/place.rb
  app/models/rule.rb
  app/models/user.rb
  config/initializers/config.rb
  config/initializers/cors.rb
  config/settings.yml
  config/settings/development.yml
  config/settings/production.yml
  config/settings/test.yml
  db/migrate/20201005152000_create_cities.rb
  db/migrate/20201005152327_create_users.rb
  db/migrate/20201005153056_create_host_informations.rb
  db/migrate/20201005154247_create_amenities.rb
  db/migrate/20201005154705_create_districts.rb
  db/migrate/20201005160040_create_places.rb
  db/migrate/20201005164043_create_bookings.rb
  db/migrate/20201008145809_create_active_storage_tables.active_storage.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/cities.rb
  spec/factories/districts.rb
  spec/factories/places.rb
Labels: documentation

#19 task-4
  app/controllers/api/v1/users_controller.rb
  app/controllers/application_controller.rb
  app/helpers/authentications_helper.rb
  app/views/api/v1/users/create.json.jbuilder
  app/views/api/v1/users/show.json.jbuilder
  config/routes.rb
  spec/requests/api/v1/users_request_spec.rb
Labels: feature

#20 Task-4.1
  app/controllers/api/v1/authentication_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/controllers/api_controller.rb
  app/controllers/application_controller.rb
  app/helpers/authentications_helper.rb
  app/lib/json_web_token.rb
  app/models/user.rb
  app/views/api/v1/authentication/show.json.jbuilder
  app/views/api/v1/users/create.json.jbuilder
  app/views/api/v1/users/show.json.jbuilder
  config/puma.rb
  config/routes.rb
Labels: bug

#21 task-5
  .rubocop.yml
  Gemfile.lock
  app/controllers/api/v1/account_activations_controller.rb
  app/controllers/api/v1/authentication_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/controllers/api_controller.rb
  app/mailers/application_mailer.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  app/views/api/v1/users/create.json.jbuilder
  app/views/layouts/_footer.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.text.erb
  app/views/user_mailer/account_activation.html.erb
  app/views/user_mailer/account_activation.text.erb
  config/environments/development.rb
  config/routes.rb
  db/migrate/20201013083543_add_activation_to_users.rb
  db/schema.rb
  db/seeds.rb
  spec/fixtures/user_mailer/account_activation
  spec/fixtures/user_mailer/password_reset
  spec/mailers/previews/user_mailer_preview.rb
  spec/mailers/user_mailer_spec.rb
  spec/requests/api/v1/account_activations_request_spec.rb
Labels: feature

#22 task-7
  Gemfile.lock
  app/controllers/api/v1/authentication_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/models/user.rb
  app/views/api/v1/users/update.json.jbuilder
  config/routes.rb
Labels: feature

#24 task-5.1
  app/controllers/api/v1/authentication_controller.rb
  app/controllers/api/v1/password_resets_controller.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  app/views/user_mailer/password_reset.html.erb
  app/views/user_mailer/password_reset.text.erb
  config/routes.rb
  db/migrate/20201025095319_add_reset_to_users.rb
  db/schema.rb
  reset_sent_at:datetime
  spec/mailers/previews/user_mailer_preview.rb
Labels: feature
