Repository quangdvn/homestay-server, pull requests merged in 2020-12, with the labels that each got.

#38 fix bug review
  Gemfile.lock
  app/controllers/api/v1/travellers/reviews_controller.rb
Labels: bug

#40 Task-18
  Gemfile.lock
  app/controllers/api/v1/hosts/switching_controller.rb
  app/controllers/api/v1/location_controller.rb
  app/controllers/api/v1/travellers/bookings_controller.rb
  app/controllers/api/v1/travellers/reviews_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/models/booking.rb
  app/models/user.rb
  app/services/application_service.rb
  app/services/booking_place_service.rb
  app/services/search_place_service.rb
  app/views/api/v1/users/create.json.jbuilder
  config/routes.rb
  config/settings.yml
Labels: enhancement

#42 Task-19
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/hosts/places_controller.rb
  app/models/place.rb
  app/services/create_place_service.rb
  app/views/api/v1/hosts/places/create.json.jbuilder
Labels: feature

#43 Home page
  app/controllers/api/v1/welcome_controller.rb
  app/views/api/v1/welcome/_index_welcome.json.jbuilder
  app/views/api/v1/welcome/index.json.jbuilder
Labels: enhancement

#44 fix bug query n+1
  app/controllers/api/v1/welcome_controller.rb
  app/models/place.rb
  app/views/api/v1/welcome/_index_welcome.json.jbuilder
  app/views/api/v1/welcome/index.json.jbuilder
Labels: bug

#45 Task12 mail to host
  app/controllers/api/v1/travellers/bookings_controller.rb
  app/mailers/booking_mailer.rb
  app/services/create_place_service.rb
  app/views/api/v1/authentication/show.json.jbuilder
  app/views/booking_mailer/notify_host.html.erb
  app/views/booking_mailer/notify_host.text.erb
  app/views/booking_mailer/notify_user.html.erb
  app/views/booking_mailer/notify_user.text.erb
  config/settings.yml
Labels: enhancement

#46 bookings_history
  app/controllers/api/v1/travellers/bookings_controller.rb
  app/views/api/v1/travellers/bookings/_index_booking.json.jbuilder
Labels: enhancement
